os: osx
language: node_js
node_js:
  - "12"

before_install:
  - npm install -g lys-compiler
	- curl https://get.wasmer.io -sSfL | sh
  - export WASMER_DIR="$HOME/.wasmer"
  - source "$WASMER_DIR/wasmer.sh"

script: make test
